### ISSUE TITLE
Consider using Activity.startNextMatchingActivity()

### ISSUE THREAD

**Issue by cketti** [ligi/KAXT#1]
Have you considered using [`Activity.startNextMatchingActivity()`](https://developer.android.com/reference/android/app/Activity.html#startNextMatchingActivity(android.content.Intent)) instead of disabling your own component in [`ActivityExtensions.rethrowIntentExcludingSelf()`](https://github.com/ligi/KAXT/blob/a883cc77585fe14623a4d93cfb2b04bc17309598/lib/src/main/java/org/ligi/kaxt/ActivityExtensions.kt#L56-L74)?

**Comment by ligi** [comment]
sounds good - will look into this when coming back home
