### ISSUE TITLE
Looks like unmock isn't needed

### ISSUE THREAD

**Issue by calvarez-ov** [ligi/KAXT#2]
Disclaimer: I don't use this project, but I was looking for any project that uses both `mockk` and `unmock`, because I'm having issues using both of them in a same project, and yours is the only project I found. 

Unfortunately for me, I didn't find any answers about how to make them play nice with each other, in this project 😄 It seems like unmock is actually not even used in this project. It's included in the buildscript classpath, and `apply plugin` is used, but:
* There's no `unmock 'org.robolectric:android-all:4.3_r2-robolectric-0'` dependency defined anywhere
* There's no `unMock` config in the module gradle file
* Completely removing unmock from the buildscript classpath and the `apply plugin` doesn't impact tests: `testDebugUnitTest` still works

So, just as an info: you can probably remove unmock from your project 😄

**Comment by ligi** [comment]
Oh thanks - seems unmock is not used anymore and I forgot to remove it. Will do it now
